### ISSUE TITLE
我调试时用手机蓝牙测试连接提示连接不上

### ISSUE THREAD

**Issue by leonfree888** [xiaoxiaohaozai/Bluetoothlib#1]
10-25 14:41:16.549 23716-23716/com.manage.manageapp D/BluetoothReceiver: 连接上了红米手机
10-25 14:41:16.659 23716-883/com.manage.manageapp W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
10-25 14:41:16.659 23716-883/com.manage.manageapp W/System.err:     at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:510)
10-25 14:41:16.659 23716-883/com.manage.manageapp W/System.err:     at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:521)
10-25 14:41:16.669 23716-883/com.manage.manageapp W/System.err:     at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:320)
10-25 14:41:16.669 23716-883/com.manage.manageapp W/System.err:     at com.chenhao.bluetoothlib.core.ClassicBluetoothModule$ConnectDeviceRunnable.run(ClassicBluetoothModule.java:151)
10-25 14:41:16.669 23716-883/com.manage.manageapp W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
10-25 14:41:16.679 23716-883/com.manage.manageapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-25 14:41:16.679 23716-883/com.manage.manageapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-25 14:41:16.679 23716-883/com.manage.manageapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-25 14:41:16.679 23716-883/com.manage.manageapp W/System.err:     at java.lang.Thread.run(Thread.java:841)
10-25 14:41:16.679 23716-883/com.manage.manageapp D/ClassicBluetoothModule: 蓝牙尝试连接失败
10-25 14:41:20.779 23716-23716/com.manage.manageapp D/BluetoothReceiver: 断开了连接红米手机

**Comment by xiaoxiaohaozai** [comment]
是连接上一会就断开了吗

**Comment by leonfree888** [comment]
对的。。我是手机对手机直连接的
