### ISSUE TITLE
连接上马上就断了

### ISSUE THREAD

**Issue by leonfree888** [xiaoxiaohaozai/Bluetoothlib#2]
10-25 15:01:07.449 30357-30357/com.manage.manageapp D/BluetoothReceiver: 连接上了huawei
10-25 15:01:11.829 30357-30357/com.manage.manageapp D/BluetoothReceiver: 断开了连接huawei
10-25 15:01:33.399 30357-30357/com.manage.manageapp D/BluetoothReceiver: 连接上了huawei
10-25 15:01:37.819 30357-30357/com.manage.manageapp D/BluetoothReceiver: 断开了连接huawei

**Comment by xiaoxiaohaozai** [comment]
你是跟蓝牙模块直接连吗，还是手机和手机连接的

**Comment by leonfree888** [comment]
我是和手机对手机直连的，没有对串口连接

**Comment by xiaoxiaohaozai** [comment]
这个手机直接连手机 确实 有点问题

**Comment by leonfree888** [comment]
那我连接串口是没有问题的吧，，就是连接硬件主板上的蓝牙

**Comment by xiaoxiaohaozai** [comment]
我这里是没问题的

**Comment by leonfree888** [comment]
知道了，，谢谢如果遇到问题在提lssues
